In [2]:
#PRIMER PUNTO (TAREA1)

# Función para generar una matriz aleatoria de tamaño 9x9 con potencias aleatorias de 2

import numpy as np
import pandas as pd 

def generar_matriz_aleatoria(n):
    matriz = np.random.randint(1, high=n+1, size=(9,9))
    matriz = 2 ** matriz
    return matriz

# Función para crear la sub-matriz B a partir de la matriz original
def crear_submatriz_b(matriz):
    return matriz[4:9, 0:4]

# Función para encontrar el promedio de la diagonal principal de una matriz
def promedio_diagonal_principal(matriz):
    diagonal_principal = np.diagonal(matriz)
    return np.mean(diagonal_principal)

# Función para encontrar el promedio de una columna específica de una matriz
def promedio_columna(matriz, columna):
    return np.mean(matriz[:, columna])

# Función para encontrar el promedio y el valor máximo de una matriz
def promedio_y_maximo(matriz):
    promedio = np.mean(matriz)
    maximo = np.max(matriz)
    return promedio, maximo

# Solicitar al usuario el valor de N
N = int(input("Ingrese el valor de N: "))

# Generar la matriz aleatoria
A = generar_matriz_aleatoria(N)
print("Matriz A:",A)


# Crear la sub-matriz B
B = crear_submatriz_b(A)
print("\nSub-matriz B:",B)


# Calcular el promedio de la diagonal principal de A
promedio_diagonal_A = promedio_diagonal_principal(A)
print("Promedio de la diagonal principal de A:", promedio_diagonal_A)

# Calcular el promedio de la segunda columna de B
promedio_columna_B = promedio_columna(B, 1)
print("Promedio de la segunda columna de B:", promedio_columna_B)

# Calcular el promedio y el valor máximo de A
promedio_A, maximo_A = promedio_y_maximo(A)

# Calcular el promedio y el valor máximo de B
promedio_B, maximo_B = promedio_y_maximo(B)

# Comparar y mostrar los resultados
resultado_A = promedio_A + maximo_A
resultado_B = promedio_B + maximo_B

print("\nResultado de A:", resultado_A)
print("Resultado de B:", resultado_B)

if resultado_A > resultado_B:
    print("El resultado de A es mayor.")
elif resultado_A < resultado_B:
    print("El resultado de B es mayor.")
else:
    print("Los resultados son iguales.")


Matriz A: [[4 4 2 2 4 2 4 4 2]
 [2 4 2 2 2 2 2 4 2]
 [4 4 2 2 4 4 4 4 2]
 [2 2 2 4 2 2 2 2 2]
 [4 2 2 4 2 4 4 2 4]
 [4 4 4 2 2 4 4 2 2]
 [2 4 4 4 2 4 2 2 4]
 [2 4 4 4 2 2 4 2 2]
 [2 2 4 4 4 2 4 4 4]]

Sub-matriz B: [[4 2 2 4]
 [4 4 4 2]
 [2 4 4 4]
 [2 4 4 4]
 [2 2 4 4]]
Promedio de la diagonal principal de A: 3.111111111111111
Promedio de la segunda columna de B: 3.2

Resultado de A: 6.962962962962963
Resultado de B: 7.3
El resultado de B es mayor.


In [3]:
#SEGUNDO PUNTO (TAREA1)

import numpy as np

def generar_matriz_aleatoria(filas,columnas, rango):
    return np.random.randint(rango[0], rango[1] + 1, size=(filas, columnas))

# Solicitar al usuario el valor de N
minimo = int(input("Ingresar valor mínimo del rango: "))
maximo = int(input("Ingresar valor máximo del rango: "))
rango = (minimo, maximo)

# Dimensiones aleatorias para la matriz
filas = np.random.randint(2, 7)
columnas = np.random.randint(2, 7)

# Generar la matriz aleatoria
matriz = generar_matriz_aleatoria(filas, columnas, rango)

# Imprimir la matriz generada
print("Matriz generada:")
print(matriz)

Matriz generada:
[[ 7 15]
 [15 12]]


In [ ]:
#TERCER PUNTO (TAREA 1)

import numpy as np

# Generar matriz A de valores aleatorios de punto flotante entre 0 y 20, de tamaño 5x5
A = np.random.uniform(0, 20, size=(5, 5))
print("Matriz A:")
print(A)

# Componentes para construir la matriz B
componentes_B = [
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7],
    [4, 5, 6, 7, 8],
    [5, 6, 7, 8, 9],
    [6, 7, 8, 9, 10],
    [7, 8, 9, 10, 11],
    [8, 9, 10, 11, 12],
    [9, 10, 11, 12, 13],
    [10, 11, 12, 13, 14]
]

# Construir matriz B a partir de los componentes dados
B = np.array(componentes_B)
print("\nMatriz B:")
print(B)

In [ ]:
#CUARTO PUNTO (TAREA 1)

def calcular_arreglo(N):
    for i in range(1, N+1):
        numero = int(''.join(str(x) for x in range(1, i+1)))
        resultado = numero * 8 + (i)
        print(f"{numero} * 8 + {i} = {resultado} (N={i})")

# Solicitar al usuario el valor de N
N = int(input("Ingrese un número entero positivo: "))

# Calcular e imprimir el arreglo
calcular_arreglo(N)

In [ ]:
#QUINTO PUNTO (TAREA 1)

def jugar_pum(N, X):
    jugador_actual = 1
    pum_actual = X
    for i in range(1, 51):
        if i == pum_actual:
            print(f"Jugador {jugador_actual}: PUM")
            pum_actual += X
        else:
            print(f"Jugador {jugador_actual}: {i}")
        jugador_actual = (jugador_actual % N) + 1

# Solicitar al usuario el número de jugadores y el número X para el PUM
N = int(input("Ingrese el número de jugadores: "))
X = int(input("Ingrese el número para el PUM (menor que 10): "))

# Ejecutar el juego PUM para los primeros 50 números
jugar_pum(N, X)

In [ ]:
#SEXTO PUNTO (TAREA 1)

def fibonacci(n):
    fibonacci_sequence = [0, 1]  # Iniciamos la secuencia con los dos primeros términos
    for i in range(2, n):
        fibonacci_sequence.append(fibonacci_sequence[-1] + fibonacci_sequence[-2])  # Calculamos el siguiente término como la suma de los dos anteriores
    return fibonacci_sequence

# Solicitar al usuario el número de términos de la sucesión que desea ver
cantidad_terminos = int(input("Ingrese la cantidad de términos de la sucesión Fibonacci que desea ver: "))

# Obtener y mostrar la sucesión de Fibonacci
resultado = fibonacci(cantidad_terminos)
print("Sucesión de Fibonacci:")
print(resultado)

In [ ]:
# SÉPTIMO PUNTO (TAREA 1)

class Plat_Juegos:
    def __init__(self):
        pass

    class Usuario:
        def __init__(self, nombre, edad, genero, horas_mes, punt_prom):
            self.nombre = nombre
            self.edad = edad
            self.genero = genero
            self.horas_mes = horas_mes
            self.punt_prom = punt_prom

        def costo_mes(self):
            P = self.punt_prom
            H = self.horas_mes
            return P * H

    class Juegos:
        def __init__(self, lanzamiento, genero, multijugador, clas_edad):
            self.lanzamiento = lanzamiento
            self.genero = genero
            self.multijugador = multijugador
            self.clas_edad = clas_edad

        def puntaje(self):
            puntaje = 0
            if 1991 <= self.lanzamiento <= 2000:
                puntaje += 2
            elif 2001 <= self.lanzamiento <= 2010:
                puntaje += 3
            elif self.lanzamiento >= 2011:
                puntaje += 4

            if self.genero == 'deportes':
                puntaje += 1
            elif self.genero == 'acción':
                puntaje += 3
            elif self.genero == 'rol':
                puntaje += 2

            if self.multijugador:
                puntaje += 4
            else:
                puntaje += 2

            if self.clas_edad == 'A':
                puntaje += 2
            elif self.clas_edad == 'B':
                puntaje += 3
            elif self.clas_edad == 'C':
                puntaje += 4

            return puntaje

# Ejemplo de uso
usuario1 = Plat_Juegos.Usuario("Juan", 25, "acción", 40, 12)
juego1 = Plat_Juegos.Juegos(1995, "acción", False, "B")

print("Puntaje del juego:", juego1.puntaje())

print("Costo del mes del usuario:", usuario1.costo_mes())